theme: jekyll-theme-giellalt
title: Dictionary for Mansi ⇒ Hungarian
description: An electronic dictionary from Mansi to Hungarian

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
